eno_morph_split1 <- eno_morph_split1 |> 
  
  # incomplete sentence
  # filter(eno_phrase_gloss_id != "^anak kamu sudah mati ada ini") |> 
  
  mutate(text_title = str_replace_all(text_title,
                                      "(Kumpul)(b)(arang)",
                                      "\\1 B\\3"),
         text_title = str_replace_all(text_title,
                                      "\\bPidah",
                                      "Pindah"),
         eno_word_pos = replace(eno_word_pos,
                                word == "Inggris",
                                "nprop"),
         word = replace(word, 
                        lex_entry == "Selus", 
                        "Selus"),
         word = replace(word, 
                        lex_entry == "Maria", 
                        "Maria"),
         word = replace(word,
                        word == "desember",
                        "Desember"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "desember",
                                     "Desember"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "mak" &
                                       eno_word_gloss_en == "mother",
                                     "ibu"),
         morph_gloss_id = replace(morph_gloss_id,
                                 morph_gloss_id == "mak" &
                                       eno_word_gloss_en == "mother",
                                     "ibu"),
         lex_entry = replace(lex_entry,
                             lex_entry == "desember",
                             "Desember"),
         morph_gloss_id = replace(morph_gloss_id,
                                  morph_gloss_id == "desember",
                                  "Desember"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(taunya)\\b",
                                               "tahunya"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(tau)\\b",
                                               "tahu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(viktor kauno)\\b",
                                               "Viktor Kauno"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "Selus kididik ka'ayar be naide karua' ki",
                                       "Selus rajin belajar karena ibunya yang menyuruhnya"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                        eno_phrase_gloss_id == "Selus rajin belajar karena ibunya yang menyuruhnya" &
                                          eno_phrase == "Selus kididik ka'ayar be naide karua' ki",
                                        "Selus studies dilligently because his mother ordered him to do so"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                        eno_phrase_gloss_eng == "Selus was hard-working at school because he mother ordered him to be",
                                        "Selus was hard-working at school because his mother ordered him to be"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_id == "0f997080-48b9-4913-b66f-606b9cb89874",
                                     "menyapu"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                        eno_phrase_gloss_id == "saya duduk di kursi",
                                        "I sit on the chair"),
         eno_word_pos = replace(eno_word_pos,
                                     eno_word_id == "0f997080-48b9-4913-b66f-606b9cb89874",
                                     "v"),
         eno_phrase_gloss_id = if_else(str_detect(eno_phrase_gloss_id, "\\b[a-z]+\\b\\s\\bnya\\b"),
                                       str_replace_all(eno_phrase_gloss_id,
                                                       "(\\b[a-z]+\\b)\\s(\\bnya\\b)",
                                                       "\\1\\2"),
                                       eno_phrase_gloss_id),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\btagkapnya\\b",
                                               "tangkapnya"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmenagambil\\b",
                                               "mengambil"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bpangil\\b",
                                               "panggil"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bi(?=ndonesia\\b)",
                                               "I"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b([a-z]+)\\s(\\-\\1)",
                                               "\\1\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b([a-z]+)\\-\\s(\\1)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bddi(?=katakan\\b)",
                                               "di"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bdiliht\\b",
                                               "dilihat"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bditubir(?=\\slaut\\b)",
                                               "di tubir"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bsekli\\b",
                                               "sekali"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "menegerjakannya",
                                               "mengerjakannya"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\b(ke|di)(sini|sana|arah)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\banak ini engga\\b",
                                               "anak ini Engga"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\b(di)(hokong)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bmereka ni belum\\b",
                                               "mereka ini belum"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\b(yang)(datang)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "^(dia)(datang)\\s(dia)(mempersiapkan)",
                                               "\\1 \\2 \\2 \\4"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_id == "0ad0d797-80ff-4957-a48d-f4d953139b53",
                                     "gone"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_id == "0ad0d797-80ff-4957-a48d-f4d953139b53",
                                     "sudah pergi"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(ke|di)(bawah|dalam|atas|sana|sini|belakang)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                                "\\b(tahun)(60)\\b",
                                                "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(ke)(tempatnya)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(ke)(depan)",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\btaun\\b",
                                               "tahun"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bjepang\\b",
                                               "Jepang"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bbelanda\\b",
                                               "Belanda"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "siapa siapa mereusak siapa mencari mereka lauk siapa cari",
                                       "siapa-siapa yang akan merusak ini, siapa yang akan mencarikan mereka lauk, siapa cari"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "tadinya itu pulau satu itu menjadi hak milik mereka ka'hua kakore",
                                       "tadinya itu, Pulau Satu itu, menjadi hak milik mereka Ka'hua Kakore"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bkal[uo]\\b",
                                               "kalau"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdinaikan\\b",
                                               "dinaikkan"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bbengkulu\\b",
                                               "Bengkulu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bjagan begitu jagan bawak\\b",
                                               "jangan begitu jangan bawa"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "kiku̇da'" & eno_word_gloss_id == "beritahu",
                                     "memberi tahu"),
         eno_word_pos = replace(eno_word_pos,
                                eno_word_gloss_id == "dikerja",
                                "v"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "dikerja",
                                     "dikejar"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "beri tahu",
                                     "beritahu"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                        eno_phrase_gloss_eng == "and next I will",
                                        "and next I will go"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\benggano\\b",
                                               "Enggano"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(sk?e?kra?ng|sekarangg)\\b",
                                               "sekarang"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bsamapai\\b",
                                               "sampai"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmenggigiti\\s\\(nya\\)",
                                               "menggigiti(nya)"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bwak kabebeok\\b",
                                               "Wak Kabebeok"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bkenpa\\b",
                                               "kenapa"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bitulh\\b",
                                               "itulah"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bkarna\\b",
                                               "karena"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bsama)\\s(sama\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\btua)\\s(tua\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\banak)\\s(anak\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bbunyi)\\s(bunyi\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(?i)(beri)a(tahu)\\b",
                                               "beritahu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(?i)begitula\\b",
                                               "begitulah"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bsaya membatu\\b",
                                               "saya membantu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bbisah\\b",
                                               "bisa"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(di)(situ)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(ini)(kan)\\b",
                                               "\\1 \\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bpaki mesin\\b",
                                               "pakai mesin"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bpohon)\\s(pohon\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bbaik)\\s(baik\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bsia)\\s(sia\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bhari)\\s(hari\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\bbenar)\\s(benar\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(\\brumah)\\s(rumah\\b)",
                                               "\\1-\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bibu\\smu\\b",
                                               "ibumu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmenyayangi\\smu\\b",
                                               "menyayangimu"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bbagima?na\\b",
                                               "bagaimana"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmusang makan kopikan musangkan\\b",
                                               "musang makan kopi, kan, musang, kan"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmengapa kamu nangis tadi\\?\\b",
                                               "mengapa kamu menangis tadi?"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\sbikinnya\\b",
                                               "dibikinnya"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\bbikin anak itu berlutut\\b",
                                               "membuat anak itu berlutut"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\spulai\\b",
                                               "di pulau"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\stempa\\skita\\sini\\b",
                                               "di tempat kita ini"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\stidur\\sdi\\ssitu\\b",
                                               "dia tidur di situ"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       word == "kana'pua" & eno_phrase_gloss_eng == "ancestors",
                                       "nenek moyang"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\sduka\\b",
                                               "di tempat duka"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bdi\\saku\\b",
                                               "diakui"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\buntuk\\smu\\b",
                                               "untukmu"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     morph_gloss_id == "belalang",
                                     "belalang"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_gloss_en == "grassohopper",
                                     "grasshopper"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "karitu̇a'" & eno_word_gloss_id == "",
                                     "menetes"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "u kidėdėhė jazz musik",
                                       "Saya (sedang) mendengarkan musik jazz"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                       eno_phrase == "u kidėdėhė jazz musik",
                                       "I (am) listen(ing) to a jazz music"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bhitung\\s\\-hitu\\b",
                                               "hitung-hitung"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bberpa\\b",
                                               "berapa"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\baja\\b",
                                               "saja"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bnambah\\b",
                                               "menambah"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmemecaghkan\\b",
                                               "memecahkan"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bberinama\\b",
                                               "beri nama"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id, 
                                               "\\balangka\\b", 
                                               "alangkah"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(?i)berserakkan\\b",
                                               "berserakan"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(?i)bigini\\b",
                                               "begini"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "berserakkan",
                                     "berserakan"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bmula\\smula\\b",
                                               "mula-mula"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\badata\\b",
                                               "adat"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\bberbendra\\b",
                                               "berbendera"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(k)(auno|ahoa|aarubi)\\b",
                                               "K\\2"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "^saudara yang sudah meninggal terdekat$",
                                               "saudara terdekat yang sudah meninggal"),
         eno_phrase_gloss_eng = str_replace_all(eno_phrase_gloss_eng,
                                               "^our closest relatives$",
                                               "our late closest relatives"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "yẽãhde man kahai' nai he a",
                                       "adiknya, laki-laki, satu ibu dengan kami (adik kandung laki-laki)"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                        eno_phrase == "yẽãhde hiu̇d kahai' na he a",
                                        "adiknya, perempuan, satu ibu dengan kami (adik kandung perempuan)"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "yẽãh kahai' na",
                                       "adik satu ibu (adik kandung)"),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                       eno_phrase == "yẽãh kahai' na",
                                       "younger sibling of the same mother"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     word == "di'ide",
                                     "be.stepped on"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "anakmu sudah mati ada ini perutnya",
                                       "anakmu sudah mati, ada ini perutnya"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "anaknya itu anak orang itu sudah tidak ada sudah mati",
                                       "anaknya itu, anak orang itu sudah tidak ada, sudah mati"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "anaknya tadi yang benar sudah mati hilang",
                                       "anaknya tadi benar-benar sudah mati, hilang"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "ke' ian iė̃'" &
                                         eno_phrase_gloss_eng == "not as strong",
                                       "Tidak terlalu kuat"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_gloss_id == "terlalu",
                                     "too"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_gloss_id == "meningalkan" &
                                       eno_word_gloss_en == "leave",
                                     "leave behind"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "meningalkan",
                                     "meninggalkan"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "omenan" & 
                                       eno_word_gloss_id == "mengali",
                                     "menggali"),
         across(matches("phrase_gloss_id"), 
                ~str_replace_all(., "\\bmeningalkan\\b", "meninggalkan")),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "Engga ke' ian ã'ĩ kin",
                                       "Engga tidak terlalu tinggi"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "Engga ke' ian piak",
                                       "Engga tidak terlalu lelah"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "hokeam" &
                                       eno_word_gloss_en == "is not",
                                     "sudah tidak ada"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     word == "hokeam" &
                                       eno_word_gloss_en == "is",
                                     "no more"),
         
         # eno_word_gloss_id = replace(eno_word_gloss_id,
         #                             lex_entry == "puru" & eno_word_gloss_id == "rumput",
         #                             "bulu"),
         # eno_word_gloss_en = replace(eno_word_gloss_en,
         #                             lex_entry == "puru" & eno_word_gloss_en == "hair",
         #                             "fur"),
         
         morph_gloss_id = replace(morph_gloss_id,
                                  morph_gloss_en == "dig" & 
                                    morph_type == "suffix" &
                                    morph_gloss_id == "mengali",
                                  "menggali"),
         
         morph_gloss_en = replace(morph_gloss_en,
                                  morph_gloss_en == "NEG" &
                                    lex_entry == "keab" &
                                    word == "keab",
                                     "not exist"),
         morph_gloss_en = replace(morph_gloss_en,
                                  morph_gloss_en == "NEG" &
                                    lex_entry == "dak" &
                                    word == "dak",
                                  "no; not"),
         morph_gloss_id = replace(morph_gloss_id,
                                  morph_gloss_id == "NEG" &
                                    lex_entry == "dak" &
                                    word %in% c("dak", "idak"),
                                  "tidak"),
         morph_gloss_en = replace(morph_gloss_en,
                                  morph_gloss_en == "like" &
                                    eno_word_gloss_id == "seperti" &
                                    morph_gloss_id == "sama",
                                  "be like"),
         
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "akeam" & 
                                       eno_word_gloss_id == "tidak ada",
                                     "kalau tidak ada"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     word == "akeam" & 
                                       eno_word_gloss_en == "NEG",
                                     "if no more"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_gloss_en == "NEG",
                                     "no; not"),
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id %in% c("NEG", "dak"),
                                     "tidak"),
         
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     eno_word_gloss_en == "NEG" &
                                       eno_word_gloss_id == "tidak ada",
                                     "not exist"),
         
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "hokekeaba" &
                                       eno_word_gloss_id == "sudah",
                                     "sudah tidak ada"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     word == "hokekeaba" &
                                       eno_word_gloss_en == "PERF",
                                     "no more"),
         
         # eno_word_gloss_id = replace(eno_word_gloss_id,
         #                             word == "hopuak" &
         #                               eno_word_gloss_id == "pergi",
         #                             "pulang"),
         
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "musyuwarah",
                                     "musyawarah"),
         
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     eno_word_gloss_id == "bermusyawar",
                                     "bermusyawarah"),
         
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase %in% c("u ki'ian", "u ki'ien") & 
                                         text_title == "Daniel Elicitation",
                                       "Saya berdiri"),
         
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                        eno_phrase %in% c("u ki'ian", "u ki'ien") & 
                                          text_title == "Daniel Elicitation",
                                       "I stand"),
         
         eno_word_gloss_id = replace(eno_word_gloss_id,
                                     word == "keam" &
                                       eno_word_gloss_id == "tidak",
                                     "tidak ada"),
         eno_word_gloss_en = replace(eno_word_gloss_en,
                                     word == "keam" &
                                       eno_word_gloss_en == "not",
                                     "not exist"),
         
         # eno_word_gloss_en = replace(eno_word_gloss_en,
         #                             eno_word_gloss_id == "seperti",
         #                             "be like"),
         
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "(?<=\\bke\\s)kahyapu\\b",
                                               "Kahyapu"),
        
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                              "^dibritahukan\\b",
                                              "diberitahukan"),
        
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "dia menduduk di buku saya",
                                       "dia duduk di buku saya"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "talinya,daunya",
                                       "talinya, daunnya"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "jadi kita jadi satu kita bawa ke",
                                       "jadi kita bersama-sama (lit. bersatu) kita pindahkan/bawa (kapalnya)"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "bilang makan siang ini disiapkan" &
                                         eno_phrase == "Selus ki'iu ionode dako'aih ean kirpu̇nka'",
                                       "Selus bilang makan malam itu disiapkan"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase_gloss_id == "anak ini data minta bagaimana",
                                       "anak ini datang minta bagaimana"),
         eno_phrase_gloss_id = str_replace_all(eno_phrase_gloss_id,
                                               "\\b(di)\\s(masak|izinkan|lakukan|pelihara|dengar|beritahukan|tinggalkannya|pilin|bawanya|kerjakan|curigai|tokok|lihat|tinggalkan|gesek|bakar|buat|tanam|katakan|cabut|makan|bilang|jalin|bawa|ikuti|pukul|suruh|akui|tempa|mainkan)\\b",
                                               "\\1\\2"),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "Engga kipapu kahu̇r ean",
                                       "Engga melarikan wanita itu."),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                      eno_phrase == "",
                                      "Engga abduct that woman."),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                      eno_phrase == "ki kipakona'",
                                      "Dia mengeluarkan (sesuatu)."),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                       eno_phrase == "ki kipakona'",
                                       "(S)he reveals (something)."),
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                      eno_phrase == "u kipakona' yuru'",
                                      "Saya mengeluarkan kepala saya."),
         eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                       eno_phrase == "u kipakona' yuru'",
                                       "I reveal my head."),
        eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                      eno_phrase == "ik kimita' pe",
                                      "Kita meminta/melamar dulu."),
        eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                      eno_phrase == "ik kimita' pe",
                                      "We ask/propose first."),
        
        eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                       eno_phrase == "kimita'au̇ kipakõ'õã'ãu̇̃ mė' kinėn asal usul",
                                       "asking to know how is the origin of"),
        eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "kimita'au̇ kipakõ'õã'ãu̇̃ mė' kinėn asal usul",
                                       "ingin tahu bagaimana asal usul"),
        
         eno_phrase_gloss_id = replace(eno_phrase_gloss_id,
                                       eno_phrase == "mako' ẽ' kirpabe'",
                                       "Cangkir itu diberdirikan."),
        eno_phrase_gloss_eng = replace(eno_phrase_gloss_eng,
                                      eno_phrase == "mako' ẽ' kirpabe'",
                                      "That cup is (caused to be) stood up."),
        
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bmenggangu\\b",
                                                      "mengganggu")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bbegaimana\\b",
                                                      "bagaimana")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bduapuluh\\b",
                                                      "dua puluh")),
         across(matches("phrase_gloss_id$"), ~str_replace_all(., "^(dua pulu)\\b", 
                                                             "\\1h")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bberkerja\\b",
                                                      "bekerja")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bdirobah\\b",
                                                      "diubah")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bdak tau nya\\b",
                                                      "tidak tahunya")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "(^tau$|\\btau\\b)",
                                                         "tahu")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bdesember\\b",
                                                      "Desember")),
         across(matches("gloss_id$"), ~str_replace_all(., "\\bIngeris\\b",
                                                      "Inggris")),
         across(matches("gloss_idn?"), ~str_replace_all(., "\\bmengahancurkan\\b",
                                                      "menghancurkan")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\b(jenis)\\.(burung|kayu)\\b",
                                                      "\\1 \\2")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bmaiankan\\b",
                                                      "mainkan")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bpermpuan\\b",
                                                      "perempuan")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bbebentuk\\b",
                                                       "berbentuk")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bmengulingkan\\b",
                                                      "menggulingkan")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bmenganggu\\b",
                                                      "mengganggu")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bmenhidupkan\\b",
                                                      "menghidupkan")),
         across(matches("gloss_idn?"), ~str_replace_all(., "\\bmengangis\\b",
                                                      "menangis")),
         across(matches("gloss_idn?"), ~str_replace_all(., "\\bnulis\\b",
                                                        "tulis/menulis")),
         
         # across(matches("gloss_id"), ~str_replace_all(., "^(ikat\\skepala)\\s(\\(bahasa\\sadat\\))",
         #                                               "\\1 tradisional \\2")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "\\bkegoto(ng)?royongan\\b",
                                                      "kegotongroyongan")),
         across(matches("gloss_idn?$"), ~str_replace_all(., "^gotong\\-royong$",
                                                        "gotong royong")),
         across(matches("^word$|^lex_entry$"), ~str_replace_all(., "^(gotong)\\-(royong)$",
                                                                "\\1 \\2")),
         across(matches("^word$|^lex_entry$"), ~str_replace_all(., "^(kegotong)\\-(royongan)$",
                                                               "\\1\\2")),
         # across(matches("gloss_id"), ~str_replace_all(., "\\b(kegotong)(royongan)\\b", "\\1-\\2")),
         # eno_word_gloss_en = replace(eno_word_gloss_en,
         #                          str_detect(morph_gloss_id, "goto(ng)?\\-?royongan"),
         #                          "communal work; working together; co-operation"),
         # morph_gram = replace(morph_gram,
         #                      word %in% c("Inggris", "Aron"),
         #                      "nprop"),
         # morph_gloss_en = replace(morph_gloss_en,
         #                          str_detect(morph_gloss_id, "goto(ng)?\\-?royongan"),
         #                          "communal work; working together; co-operation"),
         # across(matches("(word|morph)_gloss_id"), ~str_replace_all(., "\\bm[ae]njat\\b",
         #                                                           "panjat")),
         # across(matches("morph_gloss_(id|en)$"), ~str_replace_all(., "^foc$", "FOC")),
         lex_entry = replace(lex_entry, lex_entry == "manuhe",
                             "Manuhe"))

lu_form_df <- lu_form_df |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   sense_gloss_idn == "mak" &
                                     sense_gloss_en == "mother",
                                   "ibu")) |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   sense_gloss_idn == "alat untuk mengukur kelapa",
                                   "alat untuk menguliti/mencukur kelapa")) |> 
  mutate(form = replace(form, form == "manuhe", "Manuhe")) |> 
  # mutate(sense_gloss_en = replace(sense_gloss_en,
  #                                 form == "keab" &
  #                                   sense_gloss_en == "NEG",
  #                                 "not exist")) |> 
  mutate(form = replace(form, form == "desember", "Desember")) |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   sense_gloss_idn == "desember",
                                   "Desember")) |> 
  mutate(sense_gloss_en = replace(sense_gloss_en,
                                  form == "dak" &
                                    sense_gloss_en == "NEG",
                                  "no; not")) |> 
  mutate(sense_gloss_en = str_replace(sense_gloss_en, "^Aplicative", "Applicative")) |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   form == "dak" &
                                     sense_gloss_idn == "NEG",
                                   "tidak")) |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   sense_gloss_idn == "menggangu",
                                   "mengganggu")) |> 
  # mutate(sense_gloss_en = replace(sense_gloss_en,
  #                                 sense_gloss_en == "like" &
  #                                   sense_gloss_idn == "sama",
  #                                  "be like")) |> 
  mutate(sense_gloss_idn = replace(sense_gloss_idn,
                                   sense_gloss_idn == "mengali" &
                                     form == "enan" &
                                     trait == "stem" &
                                     sense_gloss_en == "dig",
                                   "menggali")) |> 
  # mutate(sense_gloss_idn = replace(sense_gloss_idn,
  #                                  is.na(sense_gloss_idn) &
  #                                    sense_gloss_en == "sea cucumber",
  #                                  "teripang; timun laut")) |> 
  # mutate(sense_gloss_idn = replace(sense_gloss_idn,
  #                                  is.na(sense_gloss_idn) &
  #                                    sense_gloss_en == "snail/sea shell",
  #                                  "siput/cangkang laut")) |> 
  # mutate(sense_gloss_idn = replace(sense_gloss_idn,
  #                                  is.na(sense_gloss_idn) &
  #                                    sense_gloss_en == "oldest",
  #                                  "tertua")) |> 
  # mutate(sense_gloss_idn = replace(sense_gloss_idn,
  #                                  is.na(sense_gloss_idn) &
  #                                    sense_gloss_en == "both",
  #                                  "keduanya")) |> 
  mutate(across(matches("gloss_idn?$"), 
                ~str_replace_all(., "\\bduapuluh\\b", "dua puluh"))) |> 
  mutate(across(matches("gloss_idn"), 
                ~str_replace_all(., "\\bdirobah\\b", "diubah"))) |> 
  mutate(across(matches("gloss_idn?$"), 
                ~str_replace_all(., "(^tau$|\\btau\\b)", "tahu"))) |> 
  mutate(across(matches("gloss_idn?$"), 
                ~str_replace_all(., "\\b(jenis)\\.(burung|kayu)\\b", "\\1 \\2"))) |> 
  mutate(across(matches("gloss_idn?$"), 
                ~str_replace_all(., "\\bbebentuk\\b", "berbentuk"))) |> 
  mutate(across(matches("gloss_idn?$"), 
                ~str_replace_all(., "\\bmenganggu\\b", "mengganggu"))) |> 
  mutate(across(matches("gloss_idn?"), ~str_replace_all(., "\\bnulis\\b",
                                                        "tulis/menulis"))) |> 
  mutate(across(matches("gloss_idn?$"), ~str_replace_all(., "\\bkegoto(ng)?royongan\\b",
                                                         "kegotongroyongan"))) |> 
  mutate(across(matches("gloss_idn?$"), ~str_replace_all(., "^gotong\\-royong$",
                                                         "gotong royong"))) |> 
  mutate(across(matches("^form$"), ~str_replace_all(., "^(gotong)\\-(royong)$",
                                                                "\\1 \\2")),
         across(matches("^form$"), ~str_replace_all(., "^(kegotong)\\-(royongan)$",
                                                                "\\1\\2")))



         # sense_gloss_idn = replace(sense_gloss_idn, sense_gloss_idn == "tau",
         #                           "tahu"),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bdesember\\b",
         #                                              "Desember")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bberkentut\\b",
         #                                              "kentut")),
         # sense_gloss_en = replace(sense_gloss_en,
         #                          sense_gloss_idn == "galah dari bambu (bamboo pole)",
         #                          "(bamboo) pole"),
         # sense_gloss_en = replace(sense_gloss_en,
         #                          sense_gloss_en == "NEG",
         #                          "no; not"),
         # sense_gloss_idn = replace(sense_gloss_idn,
         #                          sense_gloss_idn == "NEG",
         #                          "tidak"),
         # sense_gloss_idn = replace(sense_gloss_idn,
         #                           sense_gloss_idn == "nganga",
         #                           "menganga"),
         # sense_gloss_idn = replace(sense_gloss_idn,
         #                           sense_gloss_idn == "nulis" & form == "tėha'",
         #                           "tulis"),
         # sense_gloss_idn = replace(sense_gloss_idn,
         #                           sense_gloss_idn == "galah dari bambu (bamboo pole)",
         #                           "galah dari bambu"),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bmenggangu\\b",
         #                                              "mengganggu")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bbegaimana\\b",
         #                                              "bagaimana")),

         # across(matches("gloss_idn"), ~str_replace_all(., "\\bberkerja\\b",
         #                                              "bekerja")),

         # across(matches("gloss_idn"), ~str_replace_all(., "\\bdak tau nya\\b",
         #                                              "tidak tahunya")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bdesember\\b",
         #                                              "Desember")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bmengahancurkan\\b",
         #                                              "menghancurkan")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bmaiankan\\b",
         #                                              "mainkan")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bpermpuan\\b",
         #                                              "perempuan")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\blongar\\b",
         #                                               "longgar")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bmusyuwarah\\b",
         #                                               "musyawarah")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bbebentuk\\b",
         #                                               "berbentuk")),
         # across(matches("gloss_idn"), ~str_replace_all(., "^mak$",
         #                                               "ibu")),
         # across(matches("gloss_idn"), ~str_replace_all(., "^m[ae]njat$",
         #                                               "panjat")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\bmengangis\\b",
         #                                               "menangis")),
         # across(matches("gloss_idn"), ~str_replace_all(., "^meng+ang?gu$",
         #                                               "mengganggu")),
         # across(matches("gloss_idn"), ~str_replace_all(., "^(ikat\\skepala)\\s(\\(bahasa\\sadat\\))",
         #                                               "\\1 tradisional \\2")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\b(jenis)\\.(burung|kayu)\\b",
         #                                              "\\1 \\2")),
         # across(matches("gloss_idn"), ~str_replace_all(., "\\b(kegotong)(royongan)\\b", "\\1-\\2")),
         # sense_gloss_en = replace(sense_gloss_en,
         #                          str_detect(sense_gloss_idn, "goto(ng)?\\-?royongan"),
         #                          "communal work; working together; co-operation"))